---
- name: Install package dependencies
  when: ansible_pkg_mgr == "apt"
  action: apt pkg=$item state=latest update_cache=true
  with_items:
      - python-pip
      - pep8
    
# z is the new j, yo
- name: Install optparse
  git: repo=https://github.com/nk412/optparse.git
       dest=/opt/optparse

# A tool that automatically formats Python code to conform to the PEP 8 style guide
- name: Install automatic pep8 formater
  #TODO Use proper virtualenv
  pip: name=autopep8
