---
# Main entry point for dotfiles installation
# cli requirement: --extra-vars="hosts=x.x.x.x data=/path/to/config.yml"
# data.yml must define:
#   - dna_root - path where this repo was cloned
#   - user     - user namespace to apply this configuration
#   - prompt   - oh-my-zsh or liquidprompt
#   - terminal_multiplexer - screen or tmux supported

#FIXME bug in vagrantfile
#- hosts: vagrant
- hosts: '{{ hosts }}'
  gather_facts: True

  vars_files: 
    - '{{ data }}'

  user: '{{ user }}'
  #FIXME False for ansible, true for others
  sudo: False

  tasks:
    #TODO Try to replace {{ user }} with {{ whoami.stdout }}
    #- name: Determining username
      #action: shell whoami
      #register: whoami
      #sudo: False
    #FIXME Should playbooks be standalone, or refactored here ?
    - name: Install common dependencies
      when: ansible_pkg_mgr == "apt"
      action: apt pkg=$item state=latest update_cache=true
      with_items:
        - wget
        - git-core
    
    - include: shell.yml
    - include: git.yml
    - include: dev.yml
    - include: vim.yml
    #TODO Some way to control activation and desactivation
    - include: '{{ item }}'
      with_fileglob: plugins/*
