---
# Main entry point for dotfiles installation
# cli requirement: 
# ansible-playbook site.yml --ask-sudo-pass -u user \
#   --extra-vars="hosts=x.x.x.x data=/path/to/config.yml home=/home/you dna_root=some/where"
# data.yml must define:
#   - openlibs             - where projects will be stored
#   - terminal_multiplexer - screen or tmux supported
#   - shell.default        - bash or zsh
#   - shell.prompt         - oh-my-zsh or liquidprompt
#   - dev.node_version     - node version to install with nvm
#   - plugins              - list of plugins to install

# I want ansible_user_id to be the given --user $USER, not root
# https://github.com/ansible/ansible/issues/2516
- hosts: '{{ hosts }}'
  sudo: no
  gather_facts: yes

- hosts: '{{ hosts }}'
  #FIXME accelerate: true

  vars_files: 
    - '{{ data }}'

  sudo: true

  tasks:
    #TODO Should playbooks be standalone, or refactored here ?
    # Factored instructions
    - name: Install common dependencies
      when: ansible_pkg_mgr == "apt"
      action: apt pkg=$item state=latest update_cache=true
      with_items:
        - wget
        - git-core
    
    # Core components
    - include: shell.yml
    - include: git.yml
    - include: dev.yml
    - include: vim.yml

    # Plugins
    - include: '{{ item }}'
      when: "'{{ item }}'.split('/')[-1][:-4] in {{ plugins }}"
      with_fileglob: plugins/*

    # Finish him
    - name: giving back permissions to the user
      shell: chown -R {{ ansible_user_id }}:{{ ansible_user_id }} {{ home }}
    - shell: chmod -R ug+rxw,o+rx {{ home }}
