---
# Copy bins
- name: Copy utils scripts in /usr/local/bin
  copy: src={{ dna_root }}/utils/apt-git dest=/usr/local/bin/ owner={{ ansible_user_id }} mode=755
  copy: src={{ dna_root }}/utils/bizu.sh dest=/usr/local/bin/ owner={{ ansible_user_id }} mode=755
  copy: src={{ dna_root }}/utils/task-check dest=/usr/local/bin/ owner={{ ansible_user_id }} mode=755
  copy: src={{ dna_root }}/utils/view-doc dest=/usr/local/bin/ owner={{ ansible_user_id }} mode=755

# Copy templates
- name: Copy template scripts in /usr/local/bin
  template: src={{ dna_root }}/utils/openlibs-update.j2 dest=/usr/local/bin/openlibs-update owner={{ ansible_user_id }} mode=755
