---
- name: Install vim module dependencies
  when: ansible_pkg_mgr == "apt"
  action: apt pkg={{ item }} state=latest update_cache=true
  with_items:
      - vim
      - curl
      - exuberant-ctags
      - python-dev
      - xclip

- name: Install python dependencies
  pip: name=twisted
  pip: name=flake8

- name: Prepare vim configuration
  file: path={{ home }}/.vim/plugin/settings state=directory recurse=yes owner={{ ansible_user_id }} mode=600
    
- name: Copy vimrc configuration file
  copy: src={{ dna_root }}/vim/vimrc dest={{ home }}/.vimrc owner={{ ansible_user_id }} mode=600
- copy: src={{ dna_root }}/vim/plugin/bundles.vim dest={{ home }}/.vim/plugin/bundles.vim owner={{ ansible_user_id }} mode=600
- copy: src={{ dna_root }}/vim/plugin/helper.txt dest={{ home }}/.vim/plugin/helper.txt owner={{ ansible_user_id }} mode=600

- name: Copy plugins configurations
  copy: src={{ item }} dest={{ home }}/.vim/plugin/settings owner={{ ansible_user_id }} mode=600
  with_fileglob: 
      - ${dna_root}/vim/plugin/settings/*.vim
