---
- name: Install package dependencies
  when: ansible_pkg_mgr == "apt"
  action: apt pkg=$item state=latest update_cache=true
  with_items:
      - vim
      - exuberant-ctags
      - python-dev
      - xclip

- name: Install python dependencies
  pip: name=twisted
- name: Install python dependencies
  pip: name=twisted
  pip: name=flake8

- name: Prepare vim configuration
  file: path={{ home }}/.vim/plugin/settings state=directory recurse=yes owner={{ ansible_user_id }} mode=600
    
- name: Copy vimrc configuration file
  copy: src={{ dna_root }}/vim/vimrc dest={{ home }}/.vimrc owner={{ ansible_user_id }} mode=600
- copy: src={{ dna_root }}/vim/plugin/bundles.vim dest={{ home }}/.vim/plugin/bundles.vim owner={{ ansible_user_id }} mode=600
- copy: src={{ dna_root }}/vim/plugin/helper.txt dest={{ home }}/.vim/plugin/helper.txt owner={{ ansible_user_id }} mode=600

- name: Copy plugins configurations
  copy: src={{ dna_root }}/vim/plugin/settings/fugitive.vim dest={{ home }}/.vim/plugin/settings/fugitive.vim owner={{ ansible_user_id }} mode=600
- copy: src={{ dna_root }}/vim/plugin/settings/solarized.vim dest={{ home }}/.vim/plugin/settings/solarized.vim owner={{ ansible_user_id }} mode=600
- copy: src={{ dna_root }}/vim/plugin/settings/syntastic.vim dest={{ home }}/.vim/plugin/settings/syntastic.vim owner={{ ansible_user_id }} mode=600
- copy: src={{ dna_root }}/vim/plugin/settings/appearance.vim dest={{ home }}/.vim/plugin/settings/appearance.vim owner={{ ansible_user_id }} mode=600
- copy: src={{ dna_root }}/vim/plugin/settings/ctrlp.vim dest={{ home }}/.vim/plugin/settings/ctrlp.vim owner={{ ansible_user_id }} mode=600
- copy: src={{ dna_root }}/vim/plugin/settings/delimitmate.vim dest={{ home }}/.vim/plugin/settings/delimitmate.vim owner={{ ansible_user_id }} mode=600
- copy: src={{ dna_root }}/vim/plugin/settings/helper.vim dest={{ home }}/.vim/plugin/settings/helper.vim owner={{ ansible_user_id }} mode=600
