---
# Main entry point for dotfiles installation
# cli requirement:
# ansible-playbook site.yml --ask-sudo-pass -u user \
#   --extra-vars="hosts=x.x.x.x data=/path/to/config.yml home=/home/you dna_root=some/where"
# data.yml must define:
#   - openlibs             - where projects will be stored
#   - terminal_multiplexer - screen or tmux supported
#   - shell.default        - bash or zsh
#   - shell.prompt         - oh-my-zsh or liquidprompt
#   - dev.node_version     - node version to install with nvm
#   - plugins              - list of plugins to install

# I want ansible_user_id to be the given --user $USER, not root
# https://github.com/ansible/ansible/issues/2516
- hosts: "{{ hosts }}"
  sudo: no
  gather_facts: yes

- hosts: "{{ hosts }}"

  pre_tasks:
    - shell: echo 'synthetizing dna ...'

  roles:
    - dev_env

  post_tasks:
    # Finish him
    - name: giving back permissions to the user
      shell: chown -R {{ ansible_user_id }}:{{ ansible_user_id }} {{ home }}
    - shell: chmod -R ug+rxw,o+rx {{ home }}
    - shell: echo 'Done, happy hacking!'

