#
# Makefile
# xavier, 2013-07-30 07:56
#
# vim:ft=make
#

LOGS?=/tmp/dna.logs
#TODO Install accordingly to this variable
PROVIDER?=ansible
HOSTS?=127.0.0.1
DNA_ROOT?=/opt/dna

all: dependencies install

install: dependencies ansible
	@echo "Installation is done."

salt:
	@echo "Install salt master"
	curl -L http://bootstrap.saltstack.org | sudo sh -s -- -M -N
	@echo "Install salt minion"
	wget -O - http://bootstrap.saltstack.org | sudo sh
	@echo "Autorizing current machine"
	salt-key -A
	@echo "Installing minions"
	test -d /srv/salt || mkdir /srv/salt
	cp -r shell /srv/salt

ansible:
	apt-get install python-pip python-dev git-core
	@echo "[make] Install ansible, configuration manager"
	pip install PyYAML Jinja2 paramiko 2>&1 >> ${LOGS}
	test -d /opt/ansible || git clone git://github.com/ansible/ansible.git /opt/ansible
	echo ${HOSTS} > ${DNA_ROOT}/provision/ansible/hosts

	@echo "Now source /opt/ansible/hacking/env-setup"

up:
	ansible-playbook ${DNA_ROOT}/provision/ansible/shell.yml --ask-pass -u ${USER} --extra-vars="hosts=${HOSTS} data=${DNA_ROOT}/build/ansible/data.yml" -i ${DNA_ROOT}/build/ansible/hosts

dependencies:
	@echo "[make] Update cache and install packages..."
	apt-get update 2>&1 >> ${LOGS}

tests:
	@echo "Coming soon"

.PHONY: dependencies install tests
