#! /usr/bin/env python
# -*- coding: utf-8 -*-
# vim:fenc=utf-8
#
# Copyright (C) 2013 Xavier Bruhiere


'''dna-help - what the heck did dna do
Usage:
    dna-help --version
    dna-help -h | --help
    dna-help -a | --all
    dna-help bd
    dna-help vim
'''


from docopt import docopt
import dnalib


class full_help(dnalib.Help):
    help_command = 'echo "---"'
    message = ['Full list of dna available goodies',
               'dba-help --help',
               '',
               'bd - Quickly go back to a parent directory',
               'vim - see '
               'https://github.com/hivetech/dna/blob/develop/vim/doc.markdown,'
               ' or type <F2> from vim']


class bd(dnalib.Help):
    help_command = 'bd'
    message = ['Quickly go back to a parent directory in',
               'linux instead of typing "cd ../../.." repeatedly',
               '- http://vigneshwaranr.github.io/bd/']


class vim(dnalib.Help):
    help_command = 'vim -h | head -n 6'
    message = ['Check https://github.com/hivetech/dna/blob/develop/vim'
               '/doc.markdown, or type <F2> from vim']


def main(args):
    '''
    Main entry for final user
    Use arguments parsed by docopt
    '''
    if args['--all'] or args['-a']:
        full_help().show()

    elif args['bd']:
        bd().show()

    elif args['vim']:
        vim().show()


if __name__ == '__main__':
    mode = 'development'
    args = docopt(__doc__, version='dna-help v0.2.7')

    if mode == 'development':
        # Errors will be printed
        main(args)
    else:
        # Handle errors
        try:
            main(args)
        except:
            dnalib.die("running dna-help", 1)
