# Path to your oh-my-zsh configuration.
ZSH=$HOME/.oh-my-zsh

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
#ZSH_THEME="blinks"
#ZSH_THEME="cloud"
#ZSH_THEME="kardan"
#ZSH_THEME="mortalscumbag"
#ZSH_THEME="miloshadzic"
ZSH_THEME="robbyrussell"
#ZSH_THEME="af-magic"

# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"

# Set to this to use case-sensitive completion
# CASE_SENSITIVE="true"

# Comment this out to disable bi-weekly auto-update checks
# DISABLE_AUTO_UPDATE="true"

# Uncomment to change how often before auto-updates occur? (in days)
# export UPDATE_ZSH_DAYS=13

# Uncomment following line if you want to disable colors in ls
# DISABLE_LS_COLORS="true"

# Uncomment following line if you want to disable autosetting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment following line if you want to disable command autocorrection
# DISABLE_CORRECTION="true"

# Uncomment following line if you want red dots to be displayed while waiting for completion
# COMPLETION_WAITING_DOTS="true"

# Uncomment following line if you want to disable marking untracked files under
# VCS as dirty. This makes repository status check for large repositories much,
# much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
#plugins=(git battery git-flow github npm pip python screen ssh-agent vi-mode)
plugins=(git battery git-flow github npm pip python screen vi-mode)

TIME=`date +"%T"`

test -n "$ZSH" && printf '\033[0;36m'"[ $TIME ] Activating oh-my-zsh framework"'\033[0m\n'
test -n "$ZSH" && source $ZSH/oh-my-zsh.sh

# Setup external configurations
test -f $HOME/.commonrc && source $HOME/.commonrc
test -f $HOME/.customrc && source $HOME/.customrc
test -f $HOME/.common-alias && source $HOME/.common-alias
test -f $HOME/.custom-alias && source $HOME/.custom-alias
test -f $HOME/.common-functions && source $HOME/.common-functions

#TODO Move to zsh specific alias
alias bower='noglob bower'

# Fish shell like syntax highlighting for Zsh
test -d $OPENLIBS/zsh-syntax-highlighting && source $OPENLIBS/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

# ZSH port of Fish shell's history search feature
if [ -d $OPENLIBS/zsh-history-substring-search ]; then
  source $OPENLIBS/zsh-history-substring-search/zsh-history-substring-search.zsh
  # bind UP and DOWN arrow keys
  bindkey '^[[A' history-substring-search-up
  bindkey '^[[B' history-substring-search-down
fi

# NOTE Move more plugins toward antigen management ? (like antigen-bundle Tarrasch/zsh-bd)
# http://antigen.sharats.me ==================
printf '\033[0;36m'"[ $TIME ] Setup antigen"'\033[0m\n'
source ~/.antigen.zsh
antigen use oh-my-zsh
antigen bundle git
antigen bundle pip
antigen bundle command-not-found
antigen bundle chrissicool/zsh-256color
#antigen bundle zsh-users/zsh-syntax-highlighting

#antigen theme bureau
#antigen theme half-life
antigen theme cypher
#antigen theme awesomepanda
#antigen theme robbyrussell

# Auto-suggestions
antigen bundle oknowton/zsh-dwim
antigen apply
# ============================================
# https://github.com/hchbaw/auto-fu.zsh ======
printf '\033[0;36m'"[ $TIME ] Setup fuzzy zsh"'\033[0m\n'
source ~/.zsh/auto-fu; auto-fu-install
zle-line-init () {auto-fu-init;}; zle -N zle-line-init
# ============================================
# https://github.com/tarruda/zsh-autosuggestions
# Setup zsh-autosuggestions
#if [ -d $OPENLIBS/zsh-autosuggestions ]; then
  #printf '\033[0;36m'"[ $TIME ] Setup zsh autocompletion"'\033[0m\n'
  #source $OPENLIBS/zsh-autosuggestions/autosuggestions.zsh

  ## Enable autosuggestions automatically
  #zle-line-init() {
      #zle autosuggest-start
  #}
  #zle -N zle-line-init

  ## use ctrl+t to toggle autosuggestions(hopefully this wont be needed as
  ## zsh-autosuggestions is designed to be unobtrusive)
  #bindkey '^x' autosuggest-toggle
  #bindkey '^f' vi-forward-word
#fi
# ============================================
# + https://github.com/felixr/docker-zsh-completion
# ============================================
# https://github.com/zsh-users/zsh-completions
fpath=(path/to/zsh-completions/src $fpath)
# ============================================
